-- Partitioned table: users (partition key: continent)
-- LIST partitioning by continent as per infrastructure/readme.md

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  continent TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_pk PRIMARY KEY (continent, id),
  CONSTRAINT users_email_unique UNIQUE (continent, email)
) PARTITION BY LIST (continent);

-- One partition per continent
CREATE TABLE users_africa          PARTITION OF users FOR VALUES IN ('Africa');
CREATE TABLE users_antarctica      PARTITION OF users FOR VALUES IN ('Antarctica');
CREATE TABLE users_asia            PARTITION OF users FOR VALUES IN ('Asia');
CREATE TABLE users_europe          PARTITION OF users FOR VALUES IN ('Europe');
CREATE TABLE users_north_america   PARTITION OF users FOR VALUES IN ('North America');
CREATE TABLE users_south_america   PARTITION OF users FOR VALUES IN ('South America');
CREATE TABLE users_oceania         PARTITION OF users FOR VALUES IN ('Oceania');

-- Default partition for any other values
CREATE TABLE users_other PARTITION OF users DEFAULT;
